### ISSUE TITLE
Out of range exception

### ISSUE THREAD

**Issue by Indymonster** [OneThirdOff/CPU-Concept#2]
BIOS 0.0.40.41548 Loaded.
 Program 1 operation per line, prefix with linenumber to correct line.
0: LOAD 0 3
3: LOAD 1 2
6: ADD
7: SAVE 0
9: SHL 1 2
12: HALT
13: run

Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at CPU_Concept.CPU.DoLoad() in E:\Code\CPU-Concept\CPU.cs:line 97
   at CPU_Concept.CPU.Update() in E:\Code\CPU-Concept\CPU.cs:line 202
   at CPU_Concept.BIOS.RunBios() in E:\Code\CPU-Concept\BIOS.cs:line 60
   at CPU_Concept.Program.Main(String[] args) in E:\Code\CPU-Concept\Program.cs:line 12

**Comment by tstirler** [comment]
Shift left and right was not incrementing the programcounter the correct amount.
